/*
 * Copyright (c) 2026 SSG contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Ported from: lib/src/module.dart, lib/src/module/built_in.dart,
 *              lib/src/module/forwarded_view.dart, lib/src/module/shadowed_view.dart
 * Original: Copyright (c) 2019 Google Inc.
 * Original license: MIT
 *
 * Migration notes:
 *   Renames: module.dart -> Module.scala (merged family)
 *   Convention: Skeleton — public API surface only
 */
package ssg
package sass

import scala.language.implicitConversions
import ssg.sass.ast.css.CssStylesheet
import ssg.sass.value.Value

/** A Sass module — a collection of variables, functions, mixins and CSS
  * generated by evaluating a stylesheet.
  */
trait Module[T <: Callable] {

  /** The canonical URL of this module's source stylesheet, if any. */
  def url: Nullable[String]

  /** The variables defined in this module. */
  def variables: Map[String, Value]

  /** The functions defined in this module. */
  def functions: Map[String, T]

  /** The mixins defined in this module. */
  def mixins: Map[String, T]

  /** The CSS emitted by evaluating this module. */
  def css: CssStylesheet

  /** Whether this module's source was loaded from a dependency. */
  def transitivelyContainsCss: Boolean

  /** Whether this module contains any `@extend` rules. */
  def transitivelyContainsExtensions: Boolean

  /** Sets a variable's value in this module. */
  def setVariable(name: String, value: Value): Unit
}

/** A module defined in Dart/Scala code (e.g. `sass:math`). */
final class BuiltInModule[T <: Callable](
  val name: String,
  functionList: List[T] = Nil,
  mixinList: List[T] = Nil,
  variableMap: Map[String, Value] = Map.empty[String, Value]
) extends Module[T] {

  def url: Nullable[String] = s"sass:$name"

  val functions: Map[String, T] = functionList.map(f => f.name -> f).toMap

  val mixins: Map[String, T] = mixinList.map(m => m.name -> m).toMap

  private val variablesState = scala.collection.mutable.Map.from(variableMap)
  def variables: Map[String, Value] = variablesState.toMap

  // TODO: built-in modules never produce CSS
  def css: CssStylesheet = throw new UnsupportedOperationException("BuiltInModule has no CSS")

  def transitivelyContainsCss: Boolean = false
  def transitivelyContainsExtensions: Boolean = false

  def setVariable(name: String, value: Value): Unit = {
    variablesState(name) = value
  }
}

/** A view of a [[Module]] that only exposes members matching a forward rule
  * (`@forward ... show`/`hide`).
  */
final class ForwardedView[T <: Callable](
  val inner: Module[T]
  // TODO: shown/hidden sets, prefix
) extends Module[T] {

  def url: Nullable[String] = inner.url
  def variables: Map[String, Value] = inner.variables
  def functions: Map[String, T] = inner.functions
  def mixins: Map[String, T] = inner.mixins
  def css: CssStylesheet = inner.css
  def transitivelyContainsCss: Boolean = inner.transitivelyContainsCss
  def transitivelyContainsExtensions: Boolean = inner.transitivelyContainsExtensions
  def setVariable(name: String, value: Value): Unit = inner.setVariable(name, value)
}

/** A view of a [[Module]] that hides members shadowed in another module. */
final class ShadowedView[T <: Callable](
  val inner: Module[T]
  // TODO: shadowed names
) extends Module[T] {

  def url: Nullable[String] = inner.url
  def variables: Map[String, Value] = inner.variables
  def functions: Map[String, T] = inner.functions
  def mixins: Map[String, T] = inner.mixins
  def css: CssStylesheet = inner.css
  def transitivelyContainsCss: Boolean = inner.transitivelyContainsCss
  def transitivelyContainsExtensions: Boolean = inner.transitivelyContainsExtensions
  def setVariable(name: String, value: Value): Unit = inner.setVariable(name, value)
}
